targets:
  $default:
    builders:
      breeze_ui|tailwind_config_builder:
        generate_for:
          - lib/tailwind_config.dart
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
