clean:
    fvm dart run build_runner clean

get:
    fvm flutter pub get

format:
    fvm dart format $(find lib -name "*.dart" -not \( -name "*.*freezed.dart" -o -name "*.*g.dart" -o -name "*generated.dart" \) )

lint: format
    fvm dart analyze --fatal-infos --fatal-warnings

gen:
    fvm dart run build_runner build --delete-conflicting-outputs
