include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - avoid_escaping_inner_quotes
    - avoid_positional_boolean_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - directives_ordering
    - eol_at_end_of_file
    - no_literal_bool_comparisons
    - noop_primitive_operations
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_final_parameters
    - prefer_if_elements_to_conditional_expressions
    - prefer_single_quotes
    - require_trailing_commas
    - throw_in_finally
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_to_list_in_spreads
    - use_build_context_synchronously
    - use_super_parameters
